### ISSUE TITLE
Add block become True to install.yml - ensure non root ansible user will execute install.yml

### ISSUE THREAD

**Issue by ds-04** [bmillemathias/ansible-role-seaweedfs#8]
Please add, _become: True_ within _block_ to ensure _install.yml_ tasks are run as root (errors will occur if ansible user not root).

This can be used to encapsulate all the stanzas except the first in install.yml (first is:  "check the release {{ weed.version }} exists on GitHub").

```
- block:
...
... 
  become: 'True'
```

Can submit PR if needed.

**Comment by bmillemathias** [comment]
Hi there,

Thanks for reporting the issue
I've push a fix tell me it fits your needs

Best

**Comment by ds-04** [comment]
Yes working fine, thanks.

**Comment by bmillemathias** [comment]
great, thanks for your feedback
