### ISSUE TITLE
Download seaweed archive 2.30/linux_amd64.tar.gz, HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by patsevanton** [bmillemathias/ansible-role-seaweedfs#9]
Hello! Thanks for role
I try install and get error
```
TASK [bmillemathias.seaweedfs : Download seaweed archive] ******************************************************************************************************************************
Monday 28 March 2022  12:44:30 +0600 (0:00:01.314)       0:00:08.179 **********
fatal: [seaweedfs]: FAILED! => changed=false
  msg: 'Failure downloading https://github.com/chrislusf/seaweedfs/releases/download/2.30/linux_amd64.tar.gz, HTTP Error 404: Not Found'
```

Playbook
```
---
- hosts: seaweedfs
  become: yes
  roles:
    - bmillemathias.seaweedfs
```

**Comment by bmillemathias** [comment]
Hi

you need to set the version to a really recent released version (for instance `2.96`) because the seaweedfs author cannot keep all versions on github because of lack of space. 

Best

**Comment by patsevanton** [comment]
Seaweedfs have binary 2.74 and above 
https://github.com/chrislusf/seaweedfs/releases/tag/2.74

**Comment by patsevanton** [comment]
May be change version to 2.96 by default ?

**Comment by bmillemathias** [comment]
well, that I used to do, but the number of releases per month is really high, so the problem would reproduce in few days or weeks.
I've already asked to seaweedfs' author if he could host tarball on a different place where all the releases could be stored lifetime (that is the real root issue) and this was never done.

**Comment by patsevanton** [comment]
I and other people can update version periodically

**Comment by bmillemathias** [comment]
> I and other people can update version periodically

Thanks for the proposal but I don't believe in humans for keeping up with such burden.
I can update it once and let's see how it goes.
 
My point is (generally when you use ansible roles), this is the user of the role to define the version he wants to use by setting the variable `weed_version` when calling the role.

```
roles:
  - role: bmillemathias.seaweedfs
    weed_version: 2.74
``` 

What I do for my weekly test build I grab the latest version available on the github API https://github.com/bmillemathias/ansible-role-seaweedfs/blob/main/molecule/default/converge.yml
